### ISSUE TITLE
cache installed tools

### ISSUE THREAD

**Issue by robjtede** [Swatinem/rust-cache#10]
Eg. `cargo install cargo-hack` should not install fresh each time.

This can be done transparently just by caching `$HOME/.cargo/bin` (minus a few items probably) since Cargo does the necessary checks to prevent duplicate installs of the most recent version.

This would reduce CI times from installing `cargo-hack` and `cargo-tarpaulin` on actix-web by 20%.

**Comment by Swatinem** [comment]
Hm, I think https://github.com/actions-rs/install is not the way to go? (TBH, I have never used that).
I think its feasible to just cache all of `~/.cargo`, after cleaning it of course. Let me experiment with that a bit.

**Comment by Swatinem** [comment]
I played around with this a little, it was more complex than expected, but should work now

**Comment by robjtede** [comment]
That seems to work great! Thanks so much for the quick turnaround.

**Comment by Madoshakalaka** [comment]
Why is this not reflected anywhere in the README, it's an important feature!
