### ISSUE TITLE
Share cache across Git branches

### ISSUE THREAD

**Issue by stinodego** [Swatinem/rust-cache#118]
Over at [Polars](https://github.com/pola-rs/polars), we use this action extensively to speed up our various workflows.

While it's great for speeding up successive runs of the same branch, it doesn't seem to re-use the cache across branches. That's a missed opportunity, as we have many dependencies that remain constant and it's downloading the same crates over and over again for each branch.

Is there a way to configure the `key` to facilitate the caching I am looking for?

**Comment by Swatinem** [comment]
It is a well documented restriction that is being imposed by github itself:
https://github.com/Swatinem/rust-cache#cache-limits-and-control / https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

So there is nothing to do about that on my end here :-(

**Comment by stinodego** [comment]
That's unfortunate. Thanks for the explanation and the references!
