### ISSUE TITLE
Use zstd by default whenever possible

### ISSUE THREAD

**Issue by obi1kenobi** [Swatinem/rust-cache#121]
First off, thanks for the *amazing* GitHub Action! It's saved the `cargo-semver-checks` maintainers who knows how many hours of "waiting on CI time" over the lifetime of the project.

`cargo-semver-checks` has a bit of a complicated caching setup where we use both this action and `actions/cache@v3` directly. I recently noticed that while `actions/cache@v3` uses `zstd` compression, this action uses the slower and less compact gzip instead:
![image](https://user-images.githubusercontent.com/2348618/221089072-13ce9b6d-9432-4424-8391-c65d6c4b5ea2.png)

Rust projects tend to cache a lot of data, so a better + faster compressor would be a great upgrade.

I'm keeping my fingers crossed in case this is just as simple as upgrading to a newer version of `actions/cache@v3` than the one currently in the lockfile 🤞

Thanks again!

**Comment by edmorley** [comment]
Looks like 3.2.6+ is needed:
https://github.com/actions/cache/releases/tag/v3.2.6
https://github.com/actions/cache/pull/1118

**Comment by Swatinem** [comment]
Thanks for the pointer @edmorley 
I bumped all the dependencies and made a new release.
