### ISSUE TITLE
How does `mtime` handle unchanging dependencies?

### ISSUE THREAD

**Issue by max-sixty** [Swatinem/rust-cache#123]
I'm still trying to figure out what happened in https://github.com/Swatinem/rust-cache/issues/122.

Could I ask a question re:

> Before being persisted, the cache is cleaned of:
> - Any build artifacts with an mtime older than one week.

What happens if:
- There's no change in a dependency, such that its artifacts don't change
- There's a _partial_ cache hit, such that an existing cache is loaded (e.g. an existing cache `v0-rust-test-abcd-mnop` for the query `v0-rust-test-abcd-1234`)
- The action saves a new cache for the exact cache key `v0-rust-test-abcd-1234`

...are the files that are older than week old for `v0-rust-test-abcd-mnop` removed? Can this then mean that the cache is missing a bunch of files which it requires?

**Comment by Swatinem** [comment]
> There's a _partial_ cache hit, such that an existing cache is loaded

The mtime-based cleaning only happens when loading a partial cache:

https://github.com/Swatinem/rust-cache/blob/6fd3edff6979b79f87531400ad694fb7f2c84b1f/src/restore.ts#L46

No mtime-based cleaning is performed when saving it.

**Comment by max-sixty** [comment]
That's very clever, thanks. Closing!
