### ISSUE TITLE
Pre-existing caches are not updated

### ISSUE THREAD

**Issue by richvdh** [Swatinem/rust-cache#124]
Currently, if the cache exists at the start of the job, it is not updated with any changes to the `target` directory that happen during the job.

We have a moderately complicated workspace with a bunch of different crates, which get built and tested via a matrix job. The crates have plenty of shared dependencies - so it would be nice for them to benefit from a shared cache - but also some that are not shared. What we find is that the first job to run creates the cache with the dependencies for that job, but subsequent jobs do not update the cache, so their dependencies are never cached.

**Comment by Swatinem** [comment]
Updating caches is fundamentally not possible with how github caching works. Its been a long-running issue here: https://github.com/actions/toolkit/issues/505

I would recommend to just give each job its own cache. It sure takes up more size, but should also be more predictable.

**Comment by richvdh** [comment]
ah right. Thanks.
