### ISSUE TITLE
proposal: Add enable_sccache in rust-cache

### ISSUE THREAD

**Issue by Xuanwo** [Swatinem/rust-cache#125]
Hello, I am one of the contributors to [sccache](https://github.com/mozilla/sccache), a compiler caching tool similar to [ccache](https://ccache.dev/) that also supports GitHub Action caches. Sccache can cache object results based on requests. To learn more details about this, please visit [here](https://xuanwo.io/en-us/reports/2023-04/).

By utilizing sccache, we can:

- avoid uploading the entire `target`
- continue to share the same object file, even after changes to `Cargo.lock`.

Do you believe it would be advantageous to incorporate this feature into `rust-cache`? I would be pleased to submit a PR. Any feedback would be greatly appreciated. Thank you!

**Comment by Swatinem** [comment]
How exactly do you imagine to incorporate this? I thought the two projects are rather orthogonal.

**Comment by Xuanwo** [comment]
> I thought the two projects are rather orthogonal.

Ah, you're right. I misunderstood features provided by rust-cache.
