### ISSUE TITLE
Is there a way not to include job_id in the cache key ?

### ISSUE THREAD

**Issue by Roms1383** [Swatinem/rust-cache#127]
Hi, thanks for all the work on this action!
I was wondering if the `job_id` could be ignored, since I'd like to reuse cache across a couple of jobs.

**Comment by Swatinem** [comment]
You can use a `shared-key` instead, which will avoid the default job based key.

https://github.com/Swatinem/rust-cache/blob/6fd3edff6979b79f87531400ad694fb7f2c84b1f/src/config.ts#L53-L68

**Comment by Roms1383** [comment]
thanks @Swatinem! :)
