### ISSUE TITLE
What is the difference between these actions?

### ISSUE THREAD

**Issue by YoungMind1** [Swatinem/rust-cache#128]
Hello,
What is the difference between this action and [sccache](https://github.com/Mozilla-Actions/sccache-action) and [the official github action](https://github.com/actions/cache)?

I can't figure it out.
Do they work alongside each other?

**Comment by Swatinem** [comment]
It is based on the official github cache action, but specialised to Rust, so you are not caching an excessive amount of artifacts.
sccache is a different thing altogether, and I believe they do work together in some way.

**Comment by lmmx** [comment]
I was curious about this too and looked up examples where both exist in a workflow together:

- multiline regex GitHub search: [`sccache([\s\S]*?)Swatinem|Swatinem([\s\S]*?)sccache`](https://grep.app/search?f.lang=YAML&f.path=.github%2Fworkflows%2F&regexp=true&q=sccache%28%5B%5Cs%5CS%5D*%3F%29Swatinem%7CSwatinem%28%5B%5Cs%5CS%5D*%3F%29sccache)

Examples include the much discussed [Rust coreutils](https://github.com/uutils/coreutils/blob/main/.github/workflows/freebsd.yml) and [maturin](https://github.com/PyO3/maturin/blob/main/.github/workflows/test.yml)'s CI
