### ISSUE TITLE
Warning:  Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by friegger** [Swatinem/rust-cache#130]
Swatinem/rust-cache@v2.1.0 and newer fail with following error before printing the Cache Configuration, i.e. it is the only output:
```
Warning:  Error: EISDIR: illegal operation on a directory, read
```

Swatinem/rust-cache@v2.0.2 does not yield this error.

This happens with the defaults, i.e. no properties configured.
```
    - name: Setup cache
      uses: Swatinem/rust-cache@v2.1.0
```

Defaults create actual properties for execution:
```
   with:
    cache-targets: true
    prefix-key: v0-rust
```

Running on GitHub-hosted `ubuntu-20.04`.

Output of working v2.0.2 was:
```
Workspaces: 
/home/runner/work/repo/repo
Cache Paths: 
/home/runner/.cargo 
/home/runner/work/repo/repo/target 
Restore Key: 
v0-rust-build-cc72e397139d3212210d3098d019f046cf33b6c8 
Cache Key: 
v0-rust-build-cc72e397139d3212210d3098d019f046cf33b6c8-0f57a3c23b191fee29fcc6643413c12d43dc4eb8 
.. Prefix: 
- v0-rust-build 
.. Environment considered: 
- Rust Version: 1.69.0-nightly x86_64-unknown-linux-gnu (31f858d9a511f24fedb8ed997b28304fec809630) 
- CARGO_INCREMENTAL 
.. Lockfiles considered:
- /home/runner/work/repo/repo/subfolder1/Cargo.toml 
- /home/runner/work/repo/repo/subfolder2/Cargo.toml 
...more crates
```

**Comment by Swatinem** [comment]
Can you run this with logging enabled? I wonder which directory it is choking on…

**Comment by friegger** [comment]
```
##[debug]followSymbolicLinks 'false'
##[debug]followSymbolicLinks 'false'
##[debug]implicitDescendants 'true'
##[debug]matchDirectories 'true'
##[debug]omitBrokenSymbolicLinks 'true'
##[debug]Search path '/home/runner/work/repo/repo/rust-toolchain'
##[debug]Search path '/home/runner/work/repo/repo/rust-toolchain.toml'
##[debug]followSymbolicLinks 'false'
##[debug]followSymbolicLinks 'false'
##[debug]implicitDescendants 'true'
##[debug]matchDirectories 'true'
##[debug]omitBrokenSymbolicLinks 'true'
##[debug]Search path '/home/runner/work/repo/repo'
Warning:  Error: EISDIR: illegal operation on a directory, read
##[debug]Node Action run completed with exit code 0
##[debug]CACHE_ON_FAILURE='false'
##[debug]CARGO_INCREMENTAL='0'
##[debug]Set output cache-hit = false
##[debug]Finishing: Setup cache
```

**Comment by Swatinem** [comment]
That is very interesting, maybe some change in the `glob` implementation is responsible for this. Looks like somewhere when searching the main repo.

But it looks like the cache itself continues after this warning? Does it work in the end?

If it is indeed a dependency update/regression, then probably another update would magically solve this.

**Comment by friegger** [comment]
It fails and does not build a cache. I meanwhile found the issue. In our project we also have a folder named `rust-toolchain` which is not in the root of the repository. This [change to the glob pattern](https://github.com/Swatinem/rust-cache/compare/v2.0.2...v2.1.0#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012R140) now recursively checks for that name and further down the road the directory is treated as a file. A solution might be to filter everything out which is not a file after globbing.
