### ISSUE TITLE
v2 does not point to the latest v2.x version

### ISSUE THREAD

**Issue by friegger** [Swatinem/rust-cache#141]
https://github.com/Swatinem/rust-cache/releases/tag/v2 still points to https://github.com/Swatinem/rust-cache/releases/tag/v2.2.1 instead of https://github.com/Swatinem/rust-cache/releases/tag/v2.3.0.

**Comment by Swatinem** [comment]
Thanks, I noticed that myself as well. I’m waiting on the regression fix for https://github.com/Swatinem/rust-cache/issues/140 before tagging a new release and then also force updating the `v2` tag, which is the weird convention by which GitHub actions are updated.

**Comment by stevenh** [comment]
Thanks for holding off on the v2 tag update. I was hoping to get it done today, but Microsoft Windows update had different ideas, so spent the entire day getting my machine working again 😭

**Comment by Swatinem** [comment]
I released `v2.4.0` and updated the `v2` tag as well.

Thanks @stevenh for your awesome work lately :-)
