### ISSUE TITLE
Error annotations from post-run step 

### ISSUE THREAD

**Issue by Nemo157** [Swatinem/rust-cache#144]
In https://github.com/Nullus157/.github/actions/runs/5048663303 I'm seeing a bunch of error annotations:

> Error: ENOENT: no such file or directory, opendir '/home/runner/.cargo/registry/index'

stepping into one of the jobs these are coming from the post-run action when it goes to clean the registry before caching, presumably because I have no dependencies so no registry data is downloaded https://github.com/Nullus157/.github/actions/runs/5048663303/jobs/9057129303#step:7:31 (this workflow is using `rust-cache` implicitly via `actions-rust-lang/setup-rust-toolchain`).

**Comment by Swatinem** [comment]
There is a ton of places where we guard try/catch and log errors. I believe this is just a log, and does not interfere with the rest of the action, so you should be able to just ignore this. ofc it would be nicer to ignore that error completely

**Comment by Nemo157** [comment]
Yeah, this doesn't fail the action, but it's a little more than just a log, it gets shown up at the top level of the run along with actual errors which make it harder to see why a run failed.

**Comment by rivy** [comment]
I think that a missing directory/file while trying to clean and remove it should be a non-error. If so, adding something like `if ((e as any)?.code === "ENOENT") { continue; }` to the catch statements in the several "...Cleaning..." code sections in [*save.ts*](https://github.com/Swatinem/rust-cache/blob/988c164c3d0e93c4dbab36aaf5bbeb77425b2894/src/save.ts) could clear up several of the possible error messages.

https://github.com/Swatinem/rust-cache/blob/988c164c3d0e93c4dbab36aaf5bbeb77425b2894/src/save.ts#L42-L44

https://github.com/Swatinem/rust-cache/blob/988c164c3d0e93c4dbab36aaf5bbeb77425b2894/src/save.ts#L51-L53

https://github.com/Swatinem/rust-cache/blob/988c164c3d0e93c4dbab36aaf5bbeb77425b2894/src/save.ts#L58-L60

https://github.com/Swatinem/rust-cache/blob/988c164c3d0e93c4dbab36aaf5bbeb77425b2894/src/save.ts#L65-L67

**Comment by filips123** [comment]
This also happens in my project, once in a job where only rustfmt is run so no `target` is generated, and once when I conditionally build the crate. I agree with others that even though it's just a log message, it's quite annoying as it's displayed on the main workflow page:

![slika](https://github.com/Swatinem/rust-cache/assets/16626308/34b0a1ec-3e66-43f1-ab9f-a3cb54927598)

Potentially, this could also make it harder to identify real problems with the build. So, I also agree that this error message should be hidden, or somehow prevented from showing up on the main page.
