### ISSUE TITLE
Rm workspace from Cargo.lock before caching

### ISSUE THREAD

**Issue by NobodyXu** [Swatinem/rust-cache#146]
In [cargo-binstall](https://github.com/cargo-bins/cargo-binstall), we sometimes add dependency which is already present in Cargo.lock to one of the workspace.

We also have a release workflow where we create one PR for each workspace.

In both cases, Swatinem/rust-cache would upload a new cache for each pull request while nothing has really changed, which really overblown our GitHub Cache as we have >10 jobs and each cache artifact is roughly ~200MB large after compression.

I believe it can be fixed by creating a copy of Cargo.lock and remove all workspace crates from it.

Or can go one step further, create Swatinem/rust-cache's own lockfile which only contains the dependencies and their version, since this action don't care about the dependency graph, rather only the dependencies and their versions

**Comment by Swatinem** [comment]
Another option would be to set `save-if` to `false` for those workflows where you only want to consume existing caches, but never write new ones.

**Comment by NobodyXu** [comment]
> Another option would be to set `save-if` to `false` for those workflows where you only want to consume existing caches, but never write new ones.

Unfortunately just this won't help.
These workflow opens new Pull Requests, which will be merged using GitHub Merge Queue and then finally into main if they pass the merge queue CI.

Even if we disable merge queue, we would still have to create yet another >10 caches.

In `cargo-binstall`, each release we might need to create new releases for 2-5 workspaces and that will create a lot unused caches.

**Comment by NobodyXu** [comment]
> Another option would be to set `save-if` to `false` for those workflows where you only want to consume existing caches, but never write new ones.

@Swatinem The thing is the workflow that creates unnecessary caches are the workflow we run for every pull requests, merge queue and new commits to main.

There's no way to disable saving new cache in it.

**Comment by NobodyXu** [comment]
I've found [`toml-cli`](https://lib.rs/crates/toml-cli), which can be used to set all versions of workspace crates to `0.0.0`
It prints the modified toml instead of modifying in place, which fits this action's use case.

**Comment by NobodyXu** [comment]
[`cargo-lock`](https://docs.rs/cargo-lock) can be used to list all dependencies with their version and `rust-cache` could use that and filter out workspaces:

```
- addr2line 0.19.0
- adler 1.0.2
- ahash 0.7.6
- aho-corasick 1.0.2
- alloc-no-stdlib 2.0.4
- alloc-stdlib 0.2.2
```
