### ISSUE TITLE
Can (Should?) this cache be leveraged by a docker build?

### ISSUE THREAD

**Issue by Wopple** [Swatinem/rust-cache#15]
I know this may be out of scope, but I am looking to build my docker images without downloading all the dependencies every time. It is pretty expensive and slows down the process considerably, and given rust uses a lock file it feels unnecessary. The use case is specifically when copying the source to and building from the Dockerfile.

Is this supported by this tool?

yes - how can I make that work?
no - can it be supported?

Thank you

**Comment by Swatinem** [comment]
I don’t think this is something that this action can do, it is very specific to github actions.

I have seen some people use dockers layer caching for this. copy the Cargo.toml/lock into the docker image, along with an *empty* `src/main.rs`, that way docker will use the hashes of these files that will only change infrequently, and reuse that for a *later* stage that does the actual build with the full sources.

It is a bit tedious, but there should be some guides around the internet how to do it. It is also what sentry does for symbolicator:

https://github.com/getsentry/symbolicator/blob/d7e43cb9fbe1e92f8f7c3b3dc9bbed1329f7a7c7/Dockerfile#L15-L27
