### ISSUE TITLE
How to cache when Cargo.toml is in sub-directory?

### ISSUE THREAD

**Issue by AArnott** [Swatinem/rust-cache#153]
My rust project is not in the top-level directory of my repo. In the post step, this action fail with this:

> Error: Command failed: cargo metadata --all-features --format-version 1
Error: error: could not find `Cargo.toml` in `D:\a\Nerdbank.Zcash.rs\Nerdbank.Zcash.rs` or any parent directory

How can I get it to consider a subdirectory?

**Comment by NobodyXu** [comment]
You can either setup a cargo workspace, or pass the "workspaces: $subdir" to this action
