### ISSUE TITLE
Parsing error on latest release

### ISSUE THREAD

**Issue by max-sixty** [Swatinem/rust-cache#162]
FYI we're getting ~150 annotations on our jobs in the past few hours, because of warnings around parsing `Cargo.toml`.

https://github.com/PRQL/prql/actions/runs/5843523532

Our `Cargo.toml` is fairly standard, I had thought? Though not impossible it's doing something non-standard... https://github.com/PRQL/prql/blob/f84022c3e2703cc99b7237ba24fc18480f0b6744/Cargo.toml

**Comment by NobodyXu** [comment]
Tl; dr, this is the warning on CI:

```
Warning: Error parsing Cargo.toml manifest, fallback to caching entire file: SyntaxError: Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.
```

**Comment by NobodyXu** [comment]
This is caused by the toml parser, it's probably not good enough to handle every case.

We are using toml from nodejs, do you have any recommendation on a better one?

**Comment by max-sixty** [comment]
> rust-cache uses toml from nodejs, do you have any recommendation on a better one?

I'd like to be helpful but unfortunately I know very little about the nodejs ecosystem...

**Comment by max-sixty** [comment]
Yeah, the main issue is that we get 150 warnings, which somewhat invalidates the warnings we do want to see...

**Comment by NobodyXu** [comment]
Hmmm maybe adding an option to suppress these warnings?

**Comment by max-sixty** [comment]
Yeah, or reverting and just using a hash of the file, depending on how widespread this issue is...

**Comment by NobodyXu** [comment]
> Yeah, or reverting and just using a hash of the file, depending on how widespread this issue is...

Well, the warning is actually added in #156 , it can be reverted without removing the parsing part.

**Comment by NobodyXu** [comment]
I will try replacing the toml dependency with one specified in https://github.com/Swatinem/rust-cache/issues/163#issuecomment-1678253167
