### ISSUE TITLE
[question] Increase cache hits

### ISSUE THREAD

**Issue by lasantosr** [Swatinem/rust-cache#178]
Is there an option to avoid the hash of all `Cargo.lock` / `Cargo.toml` files in the cache key?

I've a workspace with multiple microservices and it's pretty common to update dependencies, include some features, etc, which produces a new cache key, when it would be much faster to restore the previous cache and just rebuild that one crate affected.

**Comment by NobodyXu** [comment]
When Cargo.lock or Cargo.toml changes, rust-cache would fetch the cache for the previous Cargo.lock/Cargo.toml and rebuild that one crate, then store it as a new cache.

**Comment by lasantosr** [comment]
Oh, then I'll have to check why I got "no cache found", I must have missed something.

Thanks!
