### ISSUE TITLE
new minor release 

### ISSUE THREAD

**Issue by vedhavyas** [Swatinem/rust-cache#18]
I would like to use the latest change to provide custom target dir. Could we get another minor release pls ?

**Comment by Swatinem** [comment]
Just published `1.3.0`. You know you can always just pin the action to a git sha, thats also enforced by some orgs for security reasons.

**Comment by vedhavyas** [comment]
> You know you can always just pin the action to a git sha, thats also enforced by some orgs for security reasons.
I didn't know that. So i can just do `@sha` instead of `@version`. Are there any examples you are aware of ?

**Comment by Swatinem** [comment]
rust-analyzer uses that:

https://github.com/rust-analyzer/rust-analyzer/blob/4cb4b23dc6dd593bc3eacf1a47a0af0d7e7062c1/.github/workflows/ci.yaml#L54
