### ISSUE TITLE
Cache growing overtime

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [Swatinem/rust-cache#181]
I want to lead by saying thank you so much for your work.

We're running into an issue where our workspace cache grows over time. From 1.2GB three weeks ago to double that two weeks later. Clearing the cache, reset the size to 1.2GB again.

I suspect the issue is that the cache is keeping unused depedency versions i.e. if you upgrade a dep, it will still keep the old version around as well.

Our caching strategy is to only cache the `main` branch to reduce cache churn (due to cache size limitations). This was a recent change, so we've only noticed this now - whereas before we were constantly evicting older caches. With this new strategy we effectively have a single, long-lived cache that keeps getting updated and therefore grows.

Is this expected? Can this action somehow do a more precise cleaning job? I've read through this [rust issue](https://github.com/rust-lang/cargo/issues/5885) which makes it sound like this isn't trivial.

**Comment by Swatinem** [comment]
yes, this is all expected behavior. The build artifacts don’t carry any version, but just an opaque hash. Its pretty much impossible which ones are needed and which aren’t.

**Comment by Mirko-von-Leipzig** [comment]
Thanks for the confirmation :) Think we'll work-around by re-creating the cache with a weekly workflow.
