### ISSUE TITLE
v2.7.3 tag missing from the repo

### ISSUE THREAD

**Issue by rillian** [Swatinem/rust-cache#185]
Hi, thanks for adding a work around for the timeouts.

In updating our references, I noticed that while there's `v2.7.3` release attached to this project, the tag and final release commit don't seem to be present in this version of the repository.

The tag is [visible through the website](https://github.com/Swatinem/rust-cache/tree/v2.7.3), but github says,
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Would it be possible to push the release tag so it's available to tooling working directly with the public repo?

**Comment by Swatinem** [comment]
Done! Looks like I forgot to push the main branch after I pushed the tag.

**Comment by rillian** [comment]
Thanks!
