### ISSUE TITLE
Strip version(s) of developed crate(s) from `Cargo.toml` before caching

### ISSUE THREAD

**Issue by eugene-babichenko** [Swatinem/rust-cache#19]
`Cargo.toml` contains the entry of the crate (crates in case of a workspace) it was generated for. For example, consider a crate `foo` with the following `Cargo.toml`:

```toml
[package]
name = "foo"
version = "0.1"

[dependencies]
...
```

It will have something like this in its `Cargo.lock` along with its dependencies:

```toml
[[package]]
name = "foo"
version = "0.1"
dependencies = [ ... ]
```

When you change a version of this crate this would result into a change of this entry. This will change the `Cargo.lock` hash although no dependencies were changed. Then an unnecessary cache miss will happen.

**Comment by Swatinem** [comment]
This wouldn’t be easily possible. Also, the action tries to reuse a previous cache on toml hash mismatches. Note that workspace crates are never cached to begin with.

**Comment by sergeyshaykhullin** [comment]
@Swatinem Can you please add more details why workspace crates are not supported? Does it might be fixed?

**Comment by Swatinem** [comment]
You can’t overwrite cache keys. That means that your workspace code would diverge from whatever is in the cache, making it less effective. Also, incremental artifacts are huge, and the download/compile tradeoff works better if you only cache external dependencies and not workspace crates which are constantly changing.
