### ISSUE TITLE
Is cache miss on any Cargo.lock change ideal?

### ISSUE THREAD

**Issue by casey** [Swatinem/rust-cache#2]
Thank you for writing this!

I am curious about whether or not it's necessary to include the hash of `Cargo.lock` files in the cache key. If some dependencies have changed but others haven't, the hash of `Cargo.lock` files will change, which will cause a cache miss. However, since some dependencies haven't changed, it might better to populate the cache, and let cargo ignore things that are out of date.

**Comment by Swatinem** [comment]
Thats what the action tries to do, I should explain this a bit in the readme, but cargo.lock/toml is the last part of the cache key, and it will partially reuse stuff, but still try to clean up as much as possible in between, though that is hard sometimes.

**Comment by casey** [comment]
I'm definitely curious how it's implemented, I was under the impression that if any part of the key didn't match, it would be a cache miss.

**Comment by Swatinem** [comment]
The action uses multiple restore keys, and they are used like this: https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key

Expand the output of the action and you can see a bit more info

**Comment by casey** [comment]
Very cool, I didn't know about that!
