### ISSUE TITLE
Cache not working on macos-latest/aarch64-apple-darwin

### ISSUE THREAD

**Issue by danhper** [Swatinem/rust-cache#203]
Hi,
I have happily been using this action to cache my Rust dependencies. However, it seems that the cache is not working with macos-latest/aarch64-apple-darwin.
Here is a sample run: https://github.com/danhper/eclair/actions/runs/10170203676/job/28128789953
It works perfectly well with macos-latest/x86_64-apple-darwin and ubuntu-latest/x86_64-unknown-linux-gnu using the exact same configuration.
Let me know if you need any more information.
Thanks!

**Comment by max-sixty** [comment]
FYI it looks like you have the same key for both darwin targets — you'll need to discriminate between them in the cache key

**Comment by danhper** [comment]
@max-sixty Thanks a lot for that, adding `key: ${{ matrix.target }}` did the trick! Sorry for the false positive!
