### ISSUE TITLE
Use separate cache for registry

### ISSUE THREAD

**Issue by jhpratt** [Swatinem/rust-cache#21]
As the crates.io registry doesn't depend on anything and does not vary between versions, would it make sense to store the registry separately? This would avoid duplicating the registry across N caches.

**Comment by Swatinem** [comment]
My first version had this, but I changed it.
The problem is that sharing across jobs can lead to races and duplication errors. Not to mention that its not obvious by which key you want to cache it. In the end it is a lot simpler to just throw everything into one cache.
