### ISSUE TITLE
Submodules not included in cache

### ISSUE THREAD

**Issue by GregHanson** [Swatinem/rust-cache#210]
I have the following Workflow segment defined:
```code
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: false

    - uses: Swatinem/rust-cache@v2
      with: 
        shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```

I noticed that after moving a dependency in my `Cargo.toml` to a new submodule (and imported as a path) in my project that my cache didn't appear to be caching anything for that module anymore.

Are submodules not supported by the tooling?  Or is there an additional directory I need to add to `cache-directories`?

**Comment by Swatinem** [comment]
local path-dependencies are not being cached. the assumption is that these workspace crates are what is constantly changing, and thus not worth caching.

**Comment by GregHanson** [comment]
I made the switch to submodule+local_path since the dependency went to a private fork

Am I correct in understanding that there isn't an exposed config option for that cache to workaround this ?

**Comment by Swatinem** [comment]
You could just use a git dependency, which are properly cached, as they are not considered to be local.

**Comment by GregHanson** [comment]
alright, I'll close.  I was able to workaround it by configuring the dependency in Cargo.toml with an ssh url and my CI with some additional steps before attempting the build:
```
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf ssh://git@github.com
          cargo --config net.git-fetch-with-cli=true fetch
```
