### ISSUE TITLE
Include env vars into the cache key

### ISSUE THREAD

**Issue by dnaka91** [Swatinem/rust-cache#27]
Hey there, thanks for this great tool! Just found out about it in [matklad's article](https://matklad.github.io/2021/09/04/fast-rust-builds.html) and it works really well for me.

I was just wondering whether it makes sense to include environment variables when creating the cache key?

For example I added the cache first and then later added the following to disable incremental builds and debug info but the cache was still considered up-to-date.
```yml
env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C debuginfo=0 -D warnings"
```

I saw that you already expose `CARGO_INCREMENTAL=0` as part of restoring the cache. Still, as other env vars can influence the generated files during compilation it might make sense to include either all or some Rust/cargo specific vars that are known to affect compilation.

**Comment by Swatinem** [comment]
This is a very good idea actually! But I think it might warrant a new version bump.

For now I think you can just `key` to bump manually.

**Comment by Swatinem** [comment]
This was implemented now in `v2`. Thanks for the contribution @dnaka91
