### ISSUE TITLE
Question: Should this action reuse cache from master?

### ISSUE THREAD

**Issue by lsunsi** [Swatinem/rust-cache#28]
I was rolling up my own cache solution before and I started using this action because it looks cleaner and honestly better than my previous setup. That said, although it works perfectly for cache within a PR (first one takes a while, following builds go quick), I think the first build of every PR is always cache-miss. Is this supposed to be the behavior?

I'm not implying anything, I'm just asking to understand better the expected behavior so I can adapt accordingly.
Thanks a lot!

**Comment by Swatinem** [comment]
As this is using the same actions toolkit package underneath, it has the same cache lookup strategy as the `actions/cache`, which is explained here: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
So yes, it should reuse caches from master without any problems.

**Comment by lsunsi** [comment]
@Swatinem thanks for the answer! i was able to get it working
