### ISSUE TITLE
Also cache: rustup

### ISSUE THREAD

**Issue by Milo123459** [Swatinem/rust-cache#29]
Maybe cache the result of `actions-rs/toolchain`?

**Comment by Swatinem** [comment]
The result of rustup is used as part of the cache key, so it needs to happen before the cache action, so it can't be cached itself. Also I doubt it would lead to any gains, since it is mostly just IO.

12.09.2021 02:10:15 Milo ***@***.***>:

**Comment by Milo123459** [comment]
Yea, you have a point!
