### ISSUE TITLE
Caching fails for cargo check & test

### ISSUE THREAD

**Issue by Defman** [Swatinem/rust-cache#30]
It seems that the cache fails for
```
cargo check
cargo test
```

https://github.com/feather-rs/feather/pull/464/checks?check_run_id=3607250247

**Comment by Swatinem** [comment]
Thanks for the report, I can take a look in about a week, as I'm currently away from my devices.

**Comment by Defman** [comment]
Hmm, now that I merged my CI changes... it successfully caches tests...

**Comment by Swatinem** [comment]
I will close this then, feel free to reopen if there are more issues.
