### ISSUE TITLE
Post Run job hangs indefinitely

### ISSUE THREAD

**Issue by TriplEight** [Swatinem/rust-cache#31]
Related to https://github.com/Swatinem/rust-cache/issues/7

Initial run finds no cache and then Post Run hangs forever:

![image](https://user-images.githubusercontent.com/17856421/133631995-a81107a3-781f-413f-ab86-7ad806298652.png)

And I get no useful logs on cancelling the job:

![image](https://user-images.githubusercontent.com/17856421/133632306-7fed70ac-fe65-4933-bf0d-9ee2fc27c8ff.png)

**Comment by Swatinem** [comment]
You can turn on detailed logging for GitHub Actions via some env vars that are documented in the GHA docs. I can help you further in about a week, currently on vacation.

**Comment by TriplEight** [comment]
I believe this can be closed, didn't observe it anymore.
