### ISSUE TITLE
Overwrite the Cache Key

### ISSUE THREAD

**Issue by omid** [Swatinem/rust-cache#32]
Just imagine that I have a project with a lot of dependencies and a `Cargo.lock` which changes every couple of days.

Does it make sense that we are able to overwrite the [generated key](https://github.com/Swatinem/rust-cache/blob/c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c/src/common.ts#L86) with completely something else, other than `Cargo.lock`?

For example, for me, it completely makes sense to cache by rust version.

PS: I might be completely wrong, I don't have so much knowledge in this.

**Comment by Swatinem** [comment]
It already caches by OS / Rust version, and it tries to partially reuse artifacts from a previous `Cargo.lock` hash. Its just that this reuse is not very precise though.
