### ISSUE TITLE
`Buffer()` is depreceated

### ISSUE THREAD

**Issue by Milo123459** [Swatinem/rust-cache#39]
https://github.com/chronotope/chrono/runs/4007495320?check_suite_focus=true#step:4:16 - Not sure how to fix it as Buffer( isn't called anywhere from a quick search.

**Comment by A248** [comment]
It appears it was fixed a couple years ago:

https://github.com/actions/toolkit/pull/265

**Comment by Swatinem** [comment]
I don’t think I have seen this myself in quite some time. Either way, its an upstream issue and I have since updated the upstream dependency a couple of times.
