### ISSUE TITLE
Feature request: support 'with:' parameter for working directory

### ISSUE THREAD

**Issue by DarkWanderer** [Swatinem/rust-cache#4]
Rationale: it would be possible to use this on repositories where a Rust module is in subdir, not in root.

Example: this [workflow](https://github.com/DarkWanderer/DynamicOperations/blob/master/.github/workflows/build.yml) builds a Rust library which is stored in subdirectory.

The "Post Run" step of the action is failing with a warning ([example](https://github.com/DarkWanderer/DynamicOperations/runs/1513042776?check_suite_focus=true)): 
`Warning:  The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101`

**Comment by Swatinem** [comment]
I added a `working-directory` input now. Also I noticed that the order of your actions is wrong. The cache action should come after selecting the toolchain, as the cache key includes the rust version hash.

I completely forgot to actually run this, I’m not sure if the `input` parameters are also passed to the `post` job, or if I would need to manually pass those through.

**Comment by DarkWanderer** [comment]
Everything [works](https://github.com/DarkWanderer/DynamicOperations/runs/1515635808?check_suite_focus=true) - thanks a lot (and especially for quick turnaround) 👍

**Comment by Swatinem** [comment]
Thats good to know. Also I noticed that you have `*` version ranges for your dependencies, and no `Cargo.lock` file. In that case the cache might become a lot less effective over time, as cargo will update to the latest versions always, without triggering a new cache key

**Comment by DarkWanderer** [comment]
Fair enough. I guess I have misinterpreted [binary vs. library](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) distinction from FAQ - while it's a "library" I will be distributing it in binary form. Looks like it'd be better for me to add it to Git - thanks for the hint.

Do you have suggestion/guidance on how to use caching correctly in CI build if I'm authoring an actual library (from above linked definition), which would have to omit Cargo.lock?

**Comment by Swatinem** [comment]
Changing your `Cargo.toml` will also bump the cache-key, and will add new dependencies to the cache. Also, since you use `stable`, it will basically reset the cache every 6 weeks with a new rust version. Other than that, not much you can do really.
