### ISSUE TITLE
Document cache limits

### ISSUE THREAD

**Issue by rukai** [Swatinem/rust-cache#41]
This looks really nice!

From reading the readme it wasnt clear to me if this has the same cache limits as actions/cache.
If it does just including this section in your own readme would be the best solution. https://github.com/actions/cache#cache-limits
Otherwise linking to that section would work too.

**Comment by Swatinem** [comment]
Yes, it uses the same code underneath. Will add something to the README to clarify that.

**Comment by Swatinem** [comment]
Well, it took some time, but I managed to link to the upstream docs now ;-)
