### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by dbanty** [Swatinem/rust-cache#50]
I'm not seeing a license for this code mentioned anywhere (e.g., in a `LICENSE` file). Is this code licensed under one of the common open source licenses (e.g., the popular Apache-2/MIT combo most Rust projects seem to use)? If not, would you consider doing so?

The reason I ask is that I'd like to try and replicate your work here in a form I can use in GitLab CI, but I, of course, don't want to violate your copyright and I'd like to give you proper attribution.

Thanks for this lovely project!!

**Comment by Swatinem** [comment]
I commited a `LICENSE` file, I tend to pick copyleft licenses for my personal projects.

As this is very much tied to GitHub, and the `actions/toolkit` packages, not sure how helpful this would be for GitLab CI though.
There are a few binary Rust projects that can do similar things, and may be more appropriate if you can host binary assets, and can have mutable caches.

**Comment by dbanty** [comment]
Thank you!

**Comment by bryanlarsen** [comment]
@dbanty did you ever create something similar for GitLab?

**Comment by dbanty** [comment]
> @dbanty did you ever create something similar for GitLab?

Nope, instead I no longer use GitLab 😅
