### ISSUE TITLE
Cache of different branches 

### ISSUE THREAD

**Issue by felixfaisal** [Swatinem/rust-cache#51]
I want to know if a cache created in one branch workflow can be used in another branch workflow provided lock and dependencies don't change.

**Comment by Swatinem** [comment]
It has the same rules as GitHubs own `cache` action:

> A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually main). For example, a cache created on the default branch would be accessible from any pull request. Also, if the branch feature-b has the base branch feature-a, a workflow triggered on feature-b would have access to caches created in the default branch (main), feature-a, and feature-b.

- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
