### ISSUE TITLE
cache cleanup failure

### ISSUE THREAD

**Issue by bergwolf** [Swatinem/rust-cache#52]
I'm getting post-job cleanup failure that causes the cache operation to exit and nothing is cached. But it is unclear what caused the failure.

```
Post job cleanup.
Warning:  The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

I'm invoking with 
```
 44       - name: Cache Nydus
 45         uses: Swatinem/rust-cache@v1
 46         with:
 47           target-dir: ./target-fusedev
 48           cache-on-failure: true
```

So looks like cache-on-failure is not working, which is another issue though.

**Comment by vdvman1** [comment]
I am also getting this warning, but I don't have `cache-on-failure` set
This is causing my builds to not be cached at all

**Comment by vdvman1** [comment]
In my case the problem was that my rust project wasn't at the root of the repository, I had to specify the `working-directory` to my project, which has fixed the problem in my repository.

**Comment by cretz** [comment]
@vdvman1 - Thanks! This fixed my problem as well.
