### ISSUE TITLE
Lockfile hash trimmed to half its length

### ISSUE THREAD

**Issue by dnaka91** [Swatinem/rust-cache#53]
While working on #35, I noticed that the lockfile hash is using **SHA-1** as algorithm. In the end, it is turned into a hex string and then trimmed to 20 characters.

As SHA-1 uses 20 bytes as output, it is doubled when turned into a hex string, resulting in a total of **40 characters**.

I was just wondering what's the reasoning behind trimming the hash to half its actual length, as it can increase the chance for clashes (duplicate hash keys for different content). 

Maybe the cache key that GitHub accepts has an upper length limit, or maybe this was done by mistake?

**Comment by Swatinem** [comment]
this now uses the full hash for both the environment and the lockfiles ;-)
