### ISSUE TITLE
failed to save cache in post step

### ISSUE THREAD

**Issue by everpcpc** [Swatinem/rust-cache#54]
```
Warning:  Unexpected token D in JSON at position 1
```
example: https://github.com/everpcpc/databend/runs/5733713479?check_suite_focus=true

It's hard to debug where the json parse failed. >_<

**Comment by Swatinem** [comment]
Indeed. Was this intermittent or is it reproducible?

**Comment by everpcpc** [comment]
I believe it's reproducible, it seems always appears in this repo:
https://github.com/datafuselabs/databend/runs/5737325164?check_suite_focus=true

**Comment by everpcpc** [comment]
It seems like issue with `cargo metadata --all-features --format-version 1`.
Adding this at last in workflow makes cache working.

**Comment by Swatinem** [comment]
This should now try/catch the `cargo metadata` invocation and also print its `stderr` to make this more obvious.
