### ISSUE TITLE
cargo can't find crate dependencies when using actions-rs/toolchain and non-`stable` release channel

### ISSUE THREAD

**Issue by tarcieri** [Swatinem/rust-cache#57]
I tried adding rust-cache to @rustsec and I'm encountering the following build failures when an explicit version (i.e. MSRV) is specified rather than `stable`:

https://github.com/rustsec/rustsec/runs/6259271728?check_suite_focus=true

```
Run cargo test --release
    Updating crates.io index
error: failed to select a version for the requirement `libgit2-sys = "^0.13.3"`
candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
location searched: crates.io index
required by package `git2 v0.14.3`
    ... which satisfies dependency `git2 = "^0.14"` (locked to 0.14.3) of package `rustsec v0.25.2 (/Users/runner/work/rustsec/rustsec/rustsec)`
    ... which satisfies path dependency `rustsec` (locked to 0.25.2) of package `rustsec-admin v0.6.1 (/Users/runner/work/rustsec/rustsec/admin)`
Error: Process completed with exit code [10](https://github.com/rustsec/rustsec/runs/6259271728?check_suite_focus=true#step:5:10)1.
```

Curiously everything is fine on `stable`.

We have `override: true` set. I'm curious if that's implicated?

**Comment by Swatinem** [comment]
The toolchain action seems fine. Also, the log indicates no cache was found, in which case the action does not really do anything.

Are you sure things work fine without the action, or with latest Rust? I’m surprised it tries to do dependency resolution, it should really just use the stuff from the logfile. What happens with `--locked`?

**Comment by tarcieri** [comment]
> Also, the log indicates no cache was found, in which case the action does not really do anything.

This is the first PR trying to add it, so I wouldn't expect the cache to be filled until we merge the PR and it runs against `main`.

> Are you sure things work fine without the action, or with latest Rust? 

The build is currently passing without `rust-cache`, and with it it works fine on `stable`. It just doesn't work if I specify e.g. `1.56` or `1.57` as the toolchain (which I'm trying to do in order to test MSRV compatibility). See: https://github.com/rustsec/rustsec/pull/551/files

> What happens with --locked?

Will try that.

**Comment by Swatinem** [comment]
On restore, the cache will do a `cargo metadata --all-features --format-version 1`, maybe that is messing with the lockfile in some way?

**Comment by tarcieri** [comment]
Looks like this issue is unrelated to `rust-cache`, sorry!

I'm still not sure what's happening but it manifested again outside of this PR.
