### ISSUE TITLE
Support for excluding paths from the cache

### ISSUE THREAD

**Issue by ryan-summers** [Swatinem/rust-cache#58]
Is it possible to explicitly exclude one of the default-cached paths?

We just hit an issue using this plugin where CI failed to detect that a build was broken in the following case:
1. Patch was made to a dependency
2. During PR process, project was pointed to the patch, CI ran, patch was cached
3. Patch was merged into dependency, branch deleted
4. Local project continued building in CI just fine because the cache found the patch, even though the referenced revision no longer existed after the PR merge

This can cause CI to report false-positive "PASS" on builds. I know this is a somewhat special case, so I was curious if it would be possible to explicitly exclude `git` dependencies from caching, even if it forces a longer build time.

**Comment by ryan-summers** [comment]
Fundamentally, it looks like there's an issue where a dependency exists in the cache, but it **no longer actually exists**. Are there other (better) ways to handle this?

**Comment by jordens** [comment]
Maybe cargo itself has the same behavior (continues using git items from cache without checking their live availability)?

**Comment by ryan-summers** [comment]
That's a good point, and it was pointed out out-of-band that this is likely because cargo can still operate on a machine if the network temporarily goes down, but dependencies are stored locally.

However, in this use case, it seems like caching dependencies, while accelerating the build, also has the downside of potentially giving false CI results, since you're using the cache instead of fetching the dependencies. The impact of this is that CI passes when the build is broken.

**Comment by jordens** [comment]
Sure.
Another similar scenario may be the case of yanked versions on `crates.io` but I don't know the `cargo` behavior in that situation.

**Comment by Swatinem** [comment]
Hm, I agree with @jordens that this sounds like `cargo` behavior. How does it behave locally if you have a populated cache, and you haven’t done a `cargo clean` in a while?

**Comment by ryan-summers** [comment]
Yeah, I think I've come to the conclusion this is more an issue with the mechanisms that cargo uses. I originally didn't notice this because my local dev machine had the exact same issue, which is indicative that this isn't an issue at all with `rust-cache`. I'll close this, since it no longer seems relevant for this repo.
