### ISSUE TITLE
Do not append `process.env.GITHUB_JOB` to the cache key if `key` is set

### ISSUE THREAD

**Issue by austinjones** [Swatinem/rust-cache#6]
If the `key` property is set, don't append `process.env.GITHUB_JOB` to the cache key.  This allows you to share a cache between jobs in a workflow.

In [my config](https://github.com/austinjones/tab-rs/blob/main/.github/workflows/ci.yml), I have a job that prepares dependencies, and others that consume the cache key.  Adding `job` to the key prevents this from working.

This could be enabled by another flag (e.g. sharedKey) if you are concerned about backwards compatibility.

**Comment by Swatinem** [comment]
Yes, a differently named flag would be a good idea here.
