### ISSUE TITLE
DependaBot not updating action

### ISSUE THREAD

**Issue by sondr3** [Swatinem/rust-cache#67]
Not sure why, but I've set up `dependabot` to automatically create PRs for updated GitHub Actions, but it seems like it cannot find the `v2` of this action.

```text
updater | INFO <job_430744624> Checking if Swatinem/rust-cache 1 needs updating
  proxy | 2022/07/29 23:32:57 [026] GET https://github.com:443/Swatinem/rust-cache.git/info/refs?service=git-upload-pack
  proxy | 2022/07/29 23:32:57 [026] * authenticating git server request (host: github.com)
  proxy | 2022/07/29 23:32:57 [026] 200 https://github.com:443/Swatinem/rust-cache.git/info/refs?service=git-upload-pack
updater | INFO <job_430744624> Latest version is 81d053bdb0871dcd3f10763c8cc60d0adc41762b
updater | INFO <job_430744624> No update needed for Swatinem/rust-cache 1
```

It could be that the updater is just slow, but normally these updates are added very quickly.

**Comment by Swatinem** [comment]
I have no idea how dependabot works in this regard. What I can say is that I keep `v2` as a branch, and not as a tag itself as github docs say. Not sure that is related?

**Comment by sondr3** [comment]
From a cursory look, I think it might be the branches that are the problem, yeah. I looked at the output from the version lookup

<details>

```
001e# service=git-upload-pack
0000015690429b3dea365e9a1b0cb82d7f98aabf3089dc63 HEAD^@multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/master filter object-format=sha1 agent=git/github-ga142b3ecc3a7
003f90429b3dea365e9a1b0cb82d7f98aabf3089dc63 refs/heads/master
003b81d053bdb0871dcd3f10763c8cc60d0adc41762b refs/heads/v1
003b6720f05bc48b77f96918929a9019fb2203ff71f8 refs/heads/v2
003fe2020cac64bc6c2833f95e29cdb3672ca7cd35b3 refs/pull/12/head
003fe985ceed8c641c7b8defb6ca9808189b0abc0967 refs/pull/14/head
003fee6bad3219569cb65d0d16ca608cb86c82183197 refs/pull/22/head
003f85515e0da76e86201877f2abbbf5168c770af1bf refs/pull/25/head
003fee5b914df1cf8ee4c5c14153871cfcade459e6ff refs/pull/34/head
003fdb260f722e757acd7d164069d278a9f902ceda89 refs/pull/35/head
003f3942d047757ec6dd8268e94277d40b85472c05cb refs/pull/40/head
003f587098aaf4be6d6ef1fbfd1d1324f2643d2631fd refs/pull/49/head
003f838480335e03ba2622678d8be2bcd0df919f4635 refs/pull/63/head
003ff04d3fad262beb8ed5792701aec16e98b3231e94 refs/pull/65/head
003ff1b1a1a78f31d729fa1ab73c64e005233fe12e58 refs/pull/68/head
003e45de10c7dec34994fffd7e046d9b2d6048734dcf refs/tags/v1.0.0
004199970e092c062358402cdc4a2a5f4e7d07b38f5c refs/tags/v1.0.0^{}
003ebc0a9afb729825a4a2a4b63e9c2e780de78a5e9d refs/tags/v1.0.1
0041a4a1d8e7a62068f6210b419d94a9198cecfea0d9 refs/tags/v1.0.1^{}
003ef560e9f6d656def9b080a70f720cafdb8fe28f85 refs/tags/v1.0.2
0041bd4d2a70178d22902962e75acbf900fef880594e refs/tags/v1.0.2^{}
003e9f37b0312594e6e4acfd2485d4da8c2a53d798d0 refs/tags/v1.1.0
00419c054053355e9f2e7af7e6e900988e0ecb7130d3 refs/tags/v1.1.0^{}
003ede7dc51db0d7049205be3e41d6e16248b0c36719 refs/tags/v1.2.0
0041a9bca6b5a60ce11e166697c7b09cfa308d92746a refs/tags/v1.2.0^{}
003e1232abb8968faf344409165de17cbf9e7f340fd8 refs/tags/v1.3.0
0041842ef286fff290e445b90b4002cc9807c3669641 refs/tags/v1.3.0^{}
003eeee60d765804d6320952071517427679bbf8f1ec refs/tags/v1.4.0
0041cb2cf0cc7c5198d3364b9630e2c3d457f160790c refs/tags/v1.4.0^{}
003e6f9b3a9a00d38fdb82797b9742458bf396cf301d refs/tags/v2.0.0
00416720f05bc48b77f96918929a9019fb2203ff71f8 refs/tags/v2.0.0^{}
0000
```

</details>

and compared it to `actions/checkout` and `actions/setup-node`, and none of them has the version number as their own branch. [`checkout`](https://github.com/actions/checkout/branches/all?query=releases) has the old versions under a `releases/v<num>` branch and the current one is in the `main` branch. So it looks like everything is primarily done via tags.

This might also be something of a feature-is-a-bug thing in dependabot, I did some searching and found one issue with this error and it also has `v1`/`v2` branches.

**Comment by LingMan** [comment]
Dependabot's current behaviour in this regard is described [here](https://github.com/dependabot/dependabot-core/issues/5017#issuecomment-1238067515). The fix would be to create `v1` and `v2` tags and then either wait for the linked issue to be resolved or rename the current `v1` and `v2` branches to something else.

Currently `v1.0.0` and `v2.0.0` tags exist. Not sure how dependabot interprets those.

**Comment by Swatinem** [comment]
TBH, using "tags" for these is very unergonomic. For one, changing a tag means that you have to override and force push it, because by design tags are supposed to be immutable.
I don’t really feel comfortable violating this invariant.

**Comment by LingMan** [comment]
According to GitHub's documentation updating tags is expected and recommended for actions:

"Move the major version tag (such as v1, v2) to point to the Git ref of the current release."
- https://docs.github.com/en/actions/creating-actions/about-custom-actions

"We recommend creating releases using semantically versioned tags – for example, v1.1.3 – and keeping major (v1) and minor (v1.1) tags current to the latest appropriate commit."
- https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions


Since the idea is to use semantic versioning for the tags, I as a consumer would very much expect a major version tag such as `v2` to change. Of course specific tags such as `v2.0.1` should stay fixed.

**Comment by Swatinem** [comment]
I chose to just create `v2` as a tag, so this should work now

**Comment by LingMan** [comment]
Thank you, however it doesn't work quite yet. Current workflows contain `@v1`, which still resolves to the branch called `v1`. Dependabot will not propose to switch away from a branch, so that needs to be converted to a tag as well.

**Comment by LingMan** [comment]
Update: Works fine now. Just got a Dependabot PR updating from v1 to v2.

Looks like https://github.com/dependabot/dependabot-core/pull/5963 fixed it.
