### ISSUE TITLE
Improve build speed

### ISSUE THREAD

**Issue by rekby** [Swatinem/rust-cache#69]
Hello, thanks for your work.

I tried the action today and surprised about it was much slower, then manual created cache rules in my project, may be my config helps to improve the action.

Cache time with manual config (exclude linter and test times) for rust 1.63.0 (in 1.56.0 situation is similar):
1. Read cache 53s
2. Build 58s
Total: 53 + 58 = 111s

Cache time with the action:
1. Read cache 21s
2. Build 4m 16s = 256s
Total: 21 + 256 = 277s

The action read cache + build slower about 2 times.

manual cached pathes:
```
        path: |
          ~/.cargo/bin/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/.package-cache
          ~/.cargo/registry/
          ~/.cargo/git/db/
          target/
```
[link to project](https://github.com/ydb-platform/ydb-rs-sdk/blob/3866a5bcd1b8c96bd72e52a063710828f367d293/.github/workflows/rust-tests.yml#L47-L54)

the actions config is empty:
```
    - name: Rust cache
       uses: Swatinem/rust-cache@v2
```
[Link to project config](https://github.com/ydb-platform/ydb-rs-sdk/blob/a75da6399a8c53a77dbfe5f2332b5660493a62b0/.github/workflows/rust-tests.yml#L42-L43)

Examples:
1. [Run with manual config](https://github.com/ydb-platform/ydb-rs-sdk/runs/7813611329?check_suite_focus=true)
2. [Run with the action](https://github.com/ydb-platform/ydb-rs-sdk/runs/7814028815?check_suite_focus=true), on hot cache (repeat build after save cache for same sources)

**Comment by Swatinem** [comment]
This is an interesting case. Maybe the difference it just in compiling your own crates, which are not being cached (it only caches dependencies).

**Comment by rekby** [comment]
May be.

Repository is [workspace](https://github.com/ydb-platform/ydb-rs-sdk/blob/d7d6f988e03eac224b6f18d1bc114dc497122c6b/Cargo.toml#L1-L1), contains 4 crates.

usually I change only one crate (ydb), but compile all crates in workspace.

**Comment by Swatinem** [comment]
I’m rather surprised why `prost-build` and `tonic-build` are not being cached. The workspace crates are not being cached intentionally, but all the dependencies should be.

**Comment by rekby** [comment]
Now the action cache about 1.5-2 times faster, then my own cache.
For rust 1.65 cache + build take about 1 minute for the action and 2-3 minute for my manual cache.

Thanks for your work.
