### ISSUE TITLE
Caching throws an error on windows GitHub Actions runners

### ISSUE THREAD

**Issue by lopopolo** [Swatinem/rust-cache#7]
Hi! Thanks for this GitHub Action. I'd like to use it in a build matrix that tests on Windows, macOS, and Linux. Things work great on macOS and Linux, but Windows fails to create a cache artifact.

GNU tar throws the following error on Windows:

```
Post job cleanup.
Saving paths:
    C:\Users\runneradmin\.cargo\registry\index
    C:\Users\runneradmin\.cargo\registry\cache
    C:\Users\runneradmin\.cargo\git
    target
Using key "v0-rust-v2-build-1.49.0-x86_64-pc-windows-msvc-e1884a8e3c3e-bb9536f437cb47ed7a45".
C:\msys64\usr\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/artichoke/artichoke --files-from manifest.txt --force-local
/usr/bin/tar: C\:\\Users\runneradmin\\.cargo\registry\\index: Cannot stat: No such file or directory
/usr/bin/tar: C\:\\Users\runneradmin\\.cargo\registry\\cache: Cannot stat: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Warning:  Tar failed with error: The process 'C:\msys64\usr\bin\tar.exe' failed with exit code 2
```

Example run: https://github.com/artichoke/artichoke/runs/1666497488?check_suite_focus=true

**Comment by Swatinem** [comment]
Interesting, `C\:\\Users\runneradmin\\.cargo\registry\\index` some backslashes ar escaped, others are not, I don’t understand why.

There was a fix recently to the upstream cache toolkit: https://github.com/actions/toolkit/commit/42b3ff04b29b03013d538e74611bec7bce5db98a But I’m not sure if that solves the problem.

Its interesting that your env is using the msys64 version. Maybe that won’t work with the action either.

Either way, I can bump the cache toolkit version, but otherwise this is an upstream problem I think. And the actions toolkit is basically abandonware :-(

Can you try with the official https://github.com/actions/cache / https://github.com/actions/toolkit version and check if it has the same issue?

**Comment by lopopolo** [comment]
This workflow used `actions/cache` on Windows and behaved as expected: https://github.com/artichoke/artichoke/runs/1664119492?check_suite_focus=true.

**Comment by lopopolo** [comment]
> Its interesting that your env is using the msys64 version. Maybe that won’t work with the action either.

I think this is because I am using `ruby/setup-ruby@v1` which messes around with the PATH.

**Comment by lopopolo** [comment]
I found these tickets that seem to suggest the problem in my case is using msys `tar` and that the latest release of `@actions/cache` does address the problem. I found a nearly identical issue in `ruby/setup-ruby`:

- https://github.com/ruby/setup-ruby/issues/102
- https://github.com/actions/toolkit/issues/632
- https://github.com/actions/toolkit/pull/670
- https://github.com/eregon/setup-ruby/commit/515629a0134e44645128f0d579a6e6ee605d6821

@Swatinem given that it looks like `@actions/cache@^1.0.5` fixes the issue, how would you like to go about releasing that update to the `v1` branch?

**Comment by Swatinem** [comment]
Updated. Can you confirm?

**Comment by lopopolo** [comment]
Looks like it worked: https://github.com/artichoke/artichoke/pull/1017/checks?check_run_id=1676834217

```
Post job cleanup.
Saving paths:
    C:\Users\runneradmin\.cargo\registry\index
    C:\Users\runneradmin\.cargo\registry\cache
    C:\Users\runneradmin\.cargo\git
    target
Using key "v0-rust-v3-build-1.49.0-x86_64-pc-windows-msvc-e1884a8e3c3e-1cd06f555e95cb78eac3".
C:\msys64\usr\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/artichoke/artichoke --files-from manifest.txt --force-local
Cache saved successfully
```

**Comment by lopopolo** [comment]
This is fixed. Thanks @Swatinem 💪
