### ISSUE TITLE
proc-macro deps aren't cached

### ISSUE THREAD

**Issue by nipunn1313** [Swatinem/rust-cache#73]
For example `thiserror-impl` or `askama-derive`

In our setup, we had a workspace where one of our crates depended on
`async-stripe` -> `thiserror` -> `thiserror-impl`

We were finding that `thiserror-impl` was not being cached here. Thus we were getting a chain of dependencies being recompiled. We were getting some partial dep caching from rust-cache, but not everything.

I turned on cargo fingerprint logging in CI and found this line:
```
2022-09-02T20:35:02.9945940Z [2022-09-02T20:35:02Z INFO  cargo::core::compiler::fingerprint] stale: missing "/home/runner/work/convex/convex/target/debug/.fingerprint/thiserror-impl-a535996c627058b5/dep-lib-thiserror-impl"
```
and later
```
[2022-09-02T20:35:03Z DEBUG cargo::core::compiler::fingerprint] fingerprint at: /home/runner/work/convex/convex/target/debug/.fingerprint/thiserror-impl-a535996c627058b5/lib-thiserror-impl
[2022-09-02T20:35:03Z INFO  cargo::core::compiler::fingerprint] fingerprint error for thiserror-impl v1.0.32/Build/TargetInner { for_host: true, proc_macro: true, ..: lib_target("thiserror-impl", ["proc-macro"], "/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-impl-1.0.32/src/lib.rs", Edition2018) }
[2022-09-02T20:35:03Z INFO  cargo::core::compiler::fingerprint]     err: failed to read `/home/runner/work/convex/convex/target/debug/.fingerprint/thiserror-impl-a535996c627058b5/lib-thiserror-impl`

    Caused by:
        No such file or directory (os error 2)
```

I did some investigation in the rust-cache source to try to debug, though I admit, it is quite complex and I may be misreading, so I'll defer to you.

I believe it's because `thiserror-impl`'s metadata has a proc-macro target like this:
```
 'targets': [{'crate_types': ['proc-macro'],
              'doc': True,
              'doctest': True,
              'edition': '2018',
              'kind': ['proc-macro'],
              'name': 'thiserror-impl',
              'src_path': '/Users/nipunn/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-impl-1.0.32/src/lib.rs',
              'test': True}],
```

Then I believe this code filters out proc-macro targets
https://github.com/Swatinem/rust-cache/blob/master/src/workspace.ts#L20

I have logs from the run. It's a private repo, so I'd rather not post it publicly, but could DM them to you if you'd want them.

[The title here is a hypothesis - it's hard to narrow down exactly what's going on]

**Comment by Swatinem** [comment]
Thanks for the report!

This is indeed weird. This should not have been cleaned up in the first place. You are right that `proc-macro` targets were missing, but the `fingerprints` are based on the crate name, not the target name which is unaffected. The `deps` are being cleaned according to either the crate name or the target names, but in this case the `thiserror-impl` target is being shadowed by the crate of the same name.

There must have been a different reason for why this was being cleaned up. I added a bit more logging and relaxed the "clean everything older than a week" heuristic.

I have some dependencies that themselves depend on `thiserror` as part of the self-tests, and it seems to work just fine.

**Comment by nipunn1313** [comment]
Ah you're right. The `proc-macro` bit doesn't explain the symptom I was seeing.

We also had the symptom mysteriously go away after changing the Cargo.lock and getting a new cache. Feel a little bit like I'm going crazy. I just looked at the logs from before and it definitely was missing the fingerprints for thiserror-impl though. I'll take a look again if we run into it again. I'll add an `ls -l` of the fingerprint directory as well as enabling `cargo::core::compiler::fingerprint`
