### ISSUE TITLE
Warnings from usage of save-state and set-output

### ISSUE THREAD

**Issue by devigned** [Swatinem/rust-cache#80]
I just noticed GitHub build warnings from save-state and set-output when using @v2.

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
and
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Just wanted to open an issue to raise awareness. Thank you for building a great GH action!

**Comment by pdegler** [comment]
Dependencies of rust-cache might need to be updated. At least the maintainers of the actions/toolkit describe this in their release notes of core [version 1.10.0](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md).

maybe other dependencies need to be updated, too?

**Comment by Swatinem** [comment]
PR was merged and I updated the dist files. Will also create a tag the coming days.
