### ISSUE TITLE
Changelog for 2.0.2 missing #85

### ISSUE THREAD

**Issue by edmorley** [Swatinem/rust-cache#88]
Hi!

The recently released 2.0.2's changelog (both in `CHANGELOG.md` and the GitHub release entry) does not mention the new features added in #85:
https://github.com/Swatinem/rust-cache/blob/master/CHANGELOG.md#202

...when it was in the 2.0.2 release:
https://github.com/Swatinem/rust-cache/compare/v2.0.1...v2.0.2

**Comment by Swatinem** [comment]
Indeed. I was in a bit of a hurry to push that new release out.
