### ISSUE TITLE
Split out `save` and `restore` actions

### ISSUE THREAD

**Issue by thomaseizinger** [Swatinem/rust-cache#94]
I really like this action for its safe defaults but I would like to use its save and restore functionality in a more controlled manner.

Specifically, I am trying to build the following:

- One workflow that only runs on `master` and always saves the cache
- A CI workflow that run for branches and pull request and always only restores the cache

The motivation for this is that I have a matrix workflow where each crate in a workspace gets tested in parallel. If I add a cache to this one, I keep blowing the maximum cache size of 10GB which means I effectively don't have any caches :(

I've built a prototype with https://github.com/MartijnHols/actions-cache but I am finding myself rebuilding a lot of the functionality already in here (cleaning of `~/.cargo`, `target` etc).

It would be great if this action could be split into a save and restore part to allow for more fine-granular control over when to save and restore caches.

**Comment by Swatinem** [comment]
I believe `save-if: false` should solve this for you.

Having `save` without `restore` does not make sense either, as the action calculates the cache key in `restore`, and does some pre-cleanup when a cache is being restored.

**Comment by thomaseizinger** [comment]
I tried `save-if: false` and the usage of the cache worked.

The problem was that I got a "cache was found and doesn't need to be saved" message whereas in my workflow, I want latest master to _always_ save the cache.

**Comment by Swatinem** [comment]
You should be able to use an expression there to make sure things are only saved when you want

**Comment by thomaseizinger** [comment]
> You should be able to use an expression there to make sure things are only saved when you want

Okay, I'll have another go at it!

**Comment by thomaseizinger** [comment]
It is working well, thanks lots for the help :)
