### ISSUE TITLE
Reduce key length?

### ISSUE THREAD

**Issue by max-sixty** [Swatinem/rust-cache#97]
Thanks for the excellent action! We use it lots in PRQL.

One very minor thing — I'm occasionally trying to understand where & why a key changed. The current keys are very long, and I _think_ would serve the same purpose being just a few characters long.

Here's an example, from https://github.com/PRQL/prql/actions/caches — it's possible but not easy to see which use different keys:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/5635139/209573478-55b628e3-ac0e-4fdc-9df6-eea58c036166.png">

**Comment by Swatinem** [comment]
Well, its using a hash of the "environment" which should be fairly stable and only change once every rustup. The second one is a hash of the lockfiles. It sure looks untidy, but thats hashes 🤷🏻‍♂️

**Comment by max-sixty** [comment]
Yes, but surely just taking the first 8 characters of the hash — like git does for showing hashes — would give us the same benefits? (Someone gets unlucky every 2 trillion changes, but otherwise...)

**Comment by Swatinem** [comment]
https://github.com/Swatinem/rust-cache/issues/53 pretty much mentioned the opposite. I do agree that you still have enough entropy with shorter hashes though.

Is it just esthetics or is there another technical reason to keep them rather short?

**Comment by max-sixty** [comment]
> Is it just esthetics or is there another technical reason to keep them rather short?

Just aesthetics! Though having it on one line would make it much easier to see differences between lines. But as in the report — very minor in the context of the full repo; fine to close.

**Comment by ForsakenHarmony** [comment]
With the max cache age of 7 days + cache size limit of 10gb, I feel like the probability of collisions is just about 0 even with a trimmed hash

having it on a single line would be nice to be able to scan which caches are from the same dependencies

**Comment by mgeisler** [comment]
I noticed this too :slightly_smiling_face:  From what I understand, we're not relying on the hashes for correctness and a hash collision will simply make Cargo build more than it otherwise would. This makes collisions benign, which suggests making the hashes short and pleasant.
